#include "main.h"

pros::Controller master(pros::E_CONTROLLER_MASTER);

pros::Motor LF(LFPORT, MOTOR_GEARSET_18, 0, MOTOR_ENCODER_ROTATIONS); // 9 11
pros::Motor LB(LBPORT, MOTOR_GEARSET_18, 0, MOTOR_ENCODER_ROTATIONS); // 20 1
pros::Motor RF(RFPORT, MOTOR_GEARSET_18, 1, MOTOR_ENCODER_ROTATIONS); // 10 20
pros::Motor RB(RBPORT, MOTOR_GEARSET_18, 1, MOTOR_ENCODER_ROTATIONS); // 19 10

pros::Motor LiftL(LIFTL, MOTOR_GEARSET_36, 0, MOTOR_ENCODER_ROTATIONS);
pros::Motor LiftR(LIFTR, MOTOR_GEARSET_36, 1, MOTOR_ENCODER_ROTATIONS);

pros::Motor ClawL(CLAWL);
pros::Motor ClawR(CLAWR);

pros::ADIPotentiometer Arm(1);
