#include "main.h"

pros::Motor LF(LFPORT, MOTOR_GEARSET_6, 0, MOTOR_ENCODER_ROTATIONS); // 9
pros::Motor LB(LBPORT, MOTOR_GEARSET_6, 0, MOTOR_ENCODER_ROTATIONS); // 10
pros::Motor RF(RFPORT, MOTOR_GEARSET_6, 0, MOTOR_ENCODER_ROTATIONS); // 1
pros::Motor RB(RBPORT, MOTOR_GEARSET_6, 0, MOTOR_ENCODER_ROTATIONS); // 2

pros::Motor Rack(RACK, MOTOR_GEARSET_18, 1, MOTOR_ENCODER_ROTATIONS);

pros::Motor Arm(ARM, MOTOR_GEARSET_36, 0, MOTOR_ENCODER_ROTATIONS);

pros::Motor RollerL(FLAPL, MOTOR_GEARSET_18, 0, MOTOR_ENCODER_ROTATIONS);
pros::Motor RollerR(FLAPR, MOTOR_GEARSET_18, 1, MOTOR_ENCODER_ROTATIONS);
